// AUTO-GENERATED by scripts/scan-feed-photos.mjs — do not edit by hand.
// Feed Photo Pool V2: structured metadata with poster/subject/scene/perspective
// Metadata lives in images/feed/MANIFEST.json; run this script to regenerate after changes.
// poster = who can post this photo | subject = who is IN the photo (null for environment/objects)
// scene = objective scene type | perspective = first_person (poster's view) or third_person (someone else in frame)
// caption = objective visual description, not a social media caption
const FEED_PHOTO_POOL = [];

if (typeof window !== 'undefined') window.FEED_PHOTO_POOL = FEED_PHOTO_POOL;
