// AUTO-GENERATED by scripts/scan-feed-photos.mjs — do not edit by hand.
// 往 images/feed/ 里丢命名好的图（owner_描述.jpg），然后跑：node scripts/scan-feed-photos.mjs
// owner ∈ ghost | soap | gaz | price | any（any = 谁都能发）；文件名的描述部分就是给模型的配图素材。
const FEED_PHOTO_POOL = [];

if (typeof window !== 'undefined') window.FEED_PHOTO_POOL = FEED_PHOTO_POOL;
